/**
 * Featured presets — по режимам агента.
 * Отображаются в PresetsRow в зависимости от выбранного режима.
 */

export type PresetMode = 'chat' | 'image' | 'video' | 'music' | 'tts' | 'utility';

export interface FeaturedPreset {
  id: string;
  title: string;
  description: string;
  mode: PresetMode;
  /** Для mode != chat */
  modelSlug?: string;
  generationMode?: string;
  parameters?: Record<string, unknown>;
  /** Для mode = chat */
  promptTemplate?: string;
  iconName?: 'MessageSquare' | 'Image' | 'Video' | 'Music' | 'Mic' | 'Sparkles' | 'Wand2' | 'Brain' | 'Code' | 'PenTool' | 'FileText' | 'Search' | 'Globe' | 'Target' | 'Zap';
  thumbnail?: string;
  badge?: 'POPULAR' | 'NEW' | 'TREND';
}

export const PRESETS_BY_MODE: Record<PresetMode, FeaturedPreset[]> = {
  chat: [
    {
      id: 'chat-eli5',
      title: 'Объясни как 5-летнему',
      description: 'Простое объяснение сложных концепций',
      mode: 'chat',
      iconName: 'Brain',
      promptTemplate: 'Объясни мне следующую концепцию так, как будто мне 5 лет, используя простые аналогии и примеры:\n\n',
      badge: 'POPULAR',
    },
    {
      id: 'chat-academic',
      title: 'Перепиши академически',
      description: 'Формальный академический стиль письма',
      mode: 'chat',
      iconName: 'FileText',
      promptTemplate: 'Перепиши следующий текст в академическом стиле, используя формальный язык и структурированное изложение:\n\n',
    },
    {
      id: 'chat-code-review',
      title: 'Найди ошибки в коде',
      description: 'Code review и исправление багов',
      mode: 'chat',
      iconName: 'Code',
      promptTemplate: 'Проведи детальный code review следующего кода. Найди все баги, потенциальные проблемы и предложи улучшения:\n\n```\n',
      badge: 'POPULAR',
    },
    {
      id: 'chat-swot',
      title: 'SWOT-анализ',
      description: 'Стратегический анализ сильных сторон',
      mode: 'chat',
      iconName: 'Target',
      promptTemplate: 'Проведи детальный SWOT-анализ следующего проекта/идеи/компании. Опиши сильные стороны, слабости, возможности и угрозы:\n\n',
    },
    {
      id: 'chat-translate',
      title: 'Перевод EN→RU с адаптацией',
      description: 'Перевод с культурной адаптацией',
      mode: 'chat',
      iconName: 'Globe',
      promptTemplate: 'Переведи следующий текст с английского на русский язык. Адаптируй культурные отсылки и идиомы так, чтобы текст звучал естественно для русскоязычной аудитории:\n\n',
    },
    {
      id: 'chat-bullets',
      title: 'Сократи до 3 буллетов',
      description: 'Краткое резюме в 3 пунктах',
      mode: 'chat',
      iconName: 'Zap',
      promptTemplate: 'Сократи следующий текст до 3 ключевых буллет-пунктов. Сохрани самое важное:\n\n',
    },
    {
      id: 'chat-startup',
      title: 'Разбери стартап-идею',
      description: 'Критический анализ бизнес-идеи',
      mode: 'chat',
      iconName: 'Sparkles',
      promptTemplate: 'Проведи критический разбор следующей стартап-идеи: рынок, конкуренты, бизнес-модель, риски и потенциал:\n\n',
      badge: 'NEW',
    },
    {
      id: 'chat-brainstorm',
      title: 'Мозговой штурм',
      description: 'Генерация идей без ограничений',
      mode: 'chat',
      iconName: 'Brain',
      promptTemplate: 'Проведи мозговой штурм на тему. Генерируй как можно больше разнообразных идей, включая нестандартные и провокационные. Тема:\n\n',
    },
    {
      id: 'chat-legal',
      title: 'Проверка договора',
      description: 'Юридический анализ документа',
      mode: 'chat',
      iconName: 'Search',
      promptTemplate: 'Проанализируй следующий договор с юридической точки зрения. Найди потенциально проблемные пункты, неясные формулировки и риски:\n\n',
    },
    {
      id: 'chat-email',
      title: 'Email от руководителя',
      description: 'Профессиональное деловое письмо',
      mode: 'chat',
      iconName: 'FileText',
      promptTemplate: 'Напиши профессиональное деловое письмо от имени руководителя. Тон: авторитетный, но уважительный. Тема письма:\n\n',
    },
  ],
  image: [
    {
      id: 'image-cinematic-portrait',
      title: 'Кинематографичный портрет',
      description: 'Реалистичный портрет с кинематографичным светом',
      mode: 'image',
      iconName: 'Image',
      modelSlug: 'flux-2-pro',
      generationMode: 't2i',
      parameters: {
        prompt: 'Cinematic portrait, soft rim lighting, dramatic shadows, shallow depth of field, 85mm lens, ultra detailed',
        aspectRatio: '2:3',
      },
      badge: 'POPULAR',
    },
    {
      id: 'image-anime-avatar',
      title: 'Аниме-аватар',
      description: 'Стилизованный аниме-портрет',
      mode: 'image',
      iconName: 'Sparkles',
      modelSlug: 'flux-2-pro',
      generationMode: 't2i',
      parameters: {
        prompt: 'Anime portrait, detailed eyes, pastel colors, soft lighting, Studio Ghibli style, high quality',
        aspectRatio: '1:1',
      },
    },
    {
      id: 'image-minimalist-logo',
      title: 'Минималистичный логотип',
      description: 'Чистый логотип в стиле минимализм',
      mode: 'image',
      iconName: 'Target',
      modelSlug: 'ideogram',
      generationMode: 't2i',
      parameters: {
        prompt: 'Minimalist logo design, clean lines, flat design, vector style, white background, professional branding',
        aspectRatio: '1:1',
      },
      badge: 'NEW',
    },
    {
      id: 'image-3d-product',
      title: '3D-рендер продукта',
      description: 'Профессиональный 3D рендер для маркетинга',
      mode: 'image',
      iconName: 'Image',
      modelSlug: 'flux-2-pro',
      generationMode: 't2i',
      parameters: {
        prompt: '3D product render, studio lighting, marble background, luxury packaging, photorealistic, ultra sharp',
        aspectRatio: '1:1',
      },
    },
    {
      id: 'image-photorealistic-interior',
      title: 'Фото-реалистичный интерьер',
      description: 'Интерьер в стиле архитектурной фотографии',
      mode: 'image',
      iconName: 'Image',
      modelSlug: 'imagen4',
      generationMode: 't2i',
      parameters: {
        prompt: 'Photorealistic interior design, natural light, modern scandinavian style, clean aesthetic, architectural photography',
        aspectRatio: '16:9',
      },
    },
    {
      id: 'image-movie-poster',
      title: 'Постер фильма',
      description: 'Кинематографичный постер в голливудском стиле',
      mode: 'image',
      iconName: 'Video',
      modelSlug: 'flux-2-pro',
      generationMode: 't2i',
      parameters: {
        prompt: 'Movie poster design, dramatic composition, cinematic lighting, bold typography space, Hollywood style, epic scale',
        aspectRatio: '2:3',
      },
      badge: 'POPULAR',
    },
    {
      id: 'image-ghibli',
      title: 'Стиль Studio Ghibli',
      description: 'Иллюстрация в стиле Хаяо Миядзаки',
      mode: 'image',
      iconName: 'Sparkles',
      modelSlug: 'flux-2-pro',
      generationMode: 't2i',
      parameters: {
        prompt: 'Studio Ghibli style illustration, lush nature, soft colors, magical atmosphere, painterly texture, Hayao Miyazaki',
        aspectRatio: '16:9',
      },
    },
    {
      id: 'image-article-illustration',
      title: 'Иллюстрация для статьи',
      description: 'Концептуальная иллюстрация для блога',
      mode: 'image',
      iconName: 'PenTool',
      modelSlug: 'ideogram',
      generationMode: 't2i',
      parameters: {
        prompt: 'Editorial illustration, conceptual art, flat design with depth, modern digital art, blog header image',
        aspectRatio: '16:9',
      },
    },
    {
      id: 'image-character-concept',
      title: 'Концепт-арт персонажа',
      description: 'Персонаж для игры или анимации',
      mode: 'image',
      iconName: 'Image',
      modelSlug: 'flux-2-pro',
      generationMode: 't2i',
      parameters: {
        prompt: 'Character concept art, full body design, detailed costume, game character sheet, dynamic pose, fantasy RPG',
        aspectRatio: '2:3',
      },
      badge: 'NEW',
    },
    {
      id: 'image-isometric-icon',
      title: 'Изометрическая иконка',
      description: '3D изометрическая иконка для UI',
      mode: 'image',
      iconName: 'Target',
      modelSlug: 'ideogram',
      generationMode: 't2i',
      parameters: {
        prompt: 'Isometric 3D icon, clean design, vibrant colors, soft shadows, app icon style, white background',
        aspectRatio: '1:1',
      },
    },
  ],
  video: [
    {
      id: 'video-drone-city',
      title: 'Дрон над городом',
      description: 'Кинематографичный дроновый облёт',
      mode: 'video',
      iconName: 'Video',
      modelSlug: 'kling-3',
      generationMode: 't2v',
      parameters: {
        prompt: 'Cinematic drone shot flying over a city at golden hour, tilt-up reveal of skyline, anamorphic lens',
        aspectRatio: '16:9',
        duration: '5',
        mode: 'pro',
      },
      badge: 'POPULAR',
    },
    {
      id: 'video-logo-intro',
      title: 'Лого-интро',
      description: 'Анимированный логотип для ютуб/видео',
      mode: 'video',
      iconName: 'Sparkles',
      modelSlug: 'kling-3',
      generationMode: 't2v',
      parameters: {
        prompt: 'Animated logo reveal, particles dissolve into logo, dark background, premium brand feel, smooth motion',
        aspectRatio: '16:9',
        duration: '5',
        mode: 'std',
      },
    },
    {
      id: 'video-reel-9x16',
      title: 'Рекламный reel 9:16',
      description: 'Вертикальный рекламный ролик для Instagram',
      mode: 'video',
      iconName: 'Video',
      modelSlug: 'hailuo-02',
      generationMode: 't2v',
      parameters: {
        prompt: 'Vertical 9:16 product advertisement, dynamic cuts, lifestyle shots, energetic pacing, modern brand',
        aspectRatio: '9:16',
      },
      badge: 'TREND',
    },
    {
      id: 'video-slowmo-product',
      title: 'Slow-mo продукта',
      description: 'Замедленная съёмка для рекламы',
      mode: 'video',
      iconName: 'Video',
      modelSlug: 'kling-3',
      generationMode: 't2v',
      parameters: {
        prompt: 'Ultra slow motion product shot, liquid splash, water droplets, luxury feel, high-speed camera effect',
        aspectRatio: '16:9',
        duration: '5',
        mode: 'pro',
      },
    },
    {
      id: 'video-anime-walk',
      title: 'Аниме-сцена ходьбы',
      description: 'Анимационная сцена в аниме-стиле',
      mode: 'video',
      iconName: 'Sparkles',
      modelSlug: 'wan-2.6',
      generationMode: 't2v',
      parameters: {
        prompt: 'Anime style walking scene, character on city street, cherry blossoms falling, cinematic anime aesthetic',
        duration: '5',
      },
      badge: 'NEW',
    },
    {
      id: 'video-timelapse-sunset',
      title: 'Таймлапс заката',
      description: '4K таймлапс с золотым часом',
      mode: 'video',
      iconName: 'Video',
      modelSlug: 'kling-3',
      generationMode: 't2v',
      parameters: {
        prompt: '4K timelapse of sunset over mountains, golden hour light, time-lapse clouds movement, dramatic sky colors',
        aspectRatio: '16:9',
        duration: '10',
        mode: 'pro',
      },
    },
    {
      id: 'video-talking-head',
      title: 'Talking head с lip-sync',
      description: 'Видео говорящей головы',
      mode: 'video',
      iconName: 'Mic',
      modelSlug: 'hailuo-02',
      generationMode: 't2v',
      parameters: {
        prompt: 'Professional talking head video, person speaking to camera, studio lighting, news anchor style',
        aspectRatio: '16:9',
      },
    },
    {
      id: 'video-ugc-review',
      title: 'UGC-обзор',
      description: 'Вертикальный UGC-стиль видео',
      mode: 'video',
      iconName: 'Video',
      modelSlug: 'hailuo-02',
      generationMode: 't2v',
      parameters: {
        prompt: 'Vertical UGC style product review, authentic person holding product, natural lighting, TikTok style',
        aspectRatio: '9:16',
      },
      badge: 'POPULAR',
    },
    {
      id: 'video-cooking-overhead',
      title: 'Кулинарное сверху',
      description: 'Overhead съёмка процесса готовки',
      mode: 'video',
      iconName: 'Video',
      modelSlug: 'kling-3',
      generationMode: 't2v',
      parameters: {
        prompt: 'Overhead food photography video, cooking process, ingredients, top-down view, natural kitchen light',
        aspectRatio: '1:1',
        duration: '5',
      },
    },
    {
      id: 'video-cyberpunk-scene',
      title: 'Кибер-панк сцена',
      description: 'Футуристическая городская сцена',
      mode: 'video',
      iconName: 'Zap',
      modelSlug: 'wan-2.6',
      generationMode: 't2v',
      parameters: {
        prompt: 'Cyberpunk city scene, neon lights reflection on wet streets, rain, futuristic Tokyo, cinematic atmosphere',
        duration: '5',
      },
      badge: 'TREND',
    },
  ],
  music: [
    {
      id: 'music-lofi-study',
      title: 'Lo-fi для учёбы',
      description: 'Расслабляющие биты для концентрации',
      mode: 'music',
      iconName: 'Music',
      modelSlug: 'suno-v5',
      generationMode: 'generate',
      parameters: {
        prompt: 'Lo-fi hip hop beats, chill study vibes, soft piano melody, vinyl crackle, cozy rainy day atmosphere, 90 BPM',
      },
      badge: 'POPULAR',
    },
    {
      id: 'music-epic-trailer',
      title: 'Эпик-трейлер',
      description: 'Эпичная музыка для кино-трейлера',
      mode: 'music',
      iconName: 'Sparkles',
      modelSlug: 'suno-v5',
      generationMode: 'generate',
      parameters: {
        prompt: 'Epic cinematic trailer music, orchestral, huge drums, brass section, building tension, Hollywood blockbuster style',
      },
    },
    {
      id: 'music-corporate-bg',
      title: 'Корпоративный фон',
      description: 'Нейтральная фоновая музыка для презентаций',
      mode: 'music',
      iconName: 'Music',
      modelSlug: 'suno-v5',
      generationMode: 'generate',
      parameters: {
        prompt: 'Corporate background music, uplifting and professional, clean production, motivational, suitable for business presentations',
      },
    },
    {
      id: 'music-hiphop-beat',
      title: 'Hip-hop инструментал',
      description: 'Trap/hip-hop бит для треков',
      mode: 'music',
      iconName: 'Zap',
      modelSlug: 'suno-v5',
      generationMode: 'generate',
      parameters: {
        prompt: 'Hip hop instrumental beat, trap hi-hats, 808 bass, sample-based, 140 BPM, dark and moody, hard-hitting',
      },
      badge: 'TREND',
    },
    {
      id: 'music-lounge-jazz',
      title: 'Lounge джаз',
      description: 'Атмосферный джаз для кафе и ресторанов',
      mode: 'music',
      iconName: 'Music',
      modelSlug: 'suno-v5',
      generationMode: 'generate',
      parameters: {
        prompt: 'Smooth lounge jazz, upright bass, soft brushed drums, mellow piano, warm saxophone, evening restaurant ambiance',
      },
    },
    {
      id: 'music-8bit-retro',
      title: '8-bit ретро',
      description: 'Chiptune в стиле ретро-игр',
      mode: 'music',
      iconName: 'Zap',
      modelSlug: 'suno-v5',
      generationMode: 'generate',
      parameters: {
        prompt: '8-bit chiptune music, retro video game style, NES/SNES era, upbeat adventure theme, catchy melody, pixelated feel',
      },
      badge: 'NEW',
    },
    {
      id: 'music-sad-piano',
      title: 'Sad piano ballad',
      description: 'Меланхоличная фортепианная баллада',
      mode: 'music',
      iconName: 'Music',
      modelSlug: 'suno-v5',
      generationMode: 'generate',
      parameters: {
        prompt: 'Sad piano ballad, emotional and melancholic, slow tempo, minimal arrangement, heartfelt, cinematic sadness',
      },
    },
    {
      id: 'music-edm-drop',
      title: 'EDM drop 130 BPM',
      description: 'Электронный дроп для клуба',
      mode: 'music',
      iconName: 'Zap',
      modelSlug: 'suno-v5',
      generationMode: 'generate',
      parameters: {
        prompt: 'EDM electronic dance music, 130 BPM, powerful drop, festival banger, synth leads, four-on-the-floor kick drum',
      },
      badge: 'POPULAR',
    },
    {
      id: 'music-ambient-meditation',
      title: 'Эмбиент медитация',
      description: 'Спокойная медитативная музыка',
      mode: 'music',
      iconName: 'Music',
      modelSlug: 'suno-v5',
      generationMode: 'generate',
      parameters: {
        prompt: 'Ambient meditation music, drone pads, gentle nature sounds, binaural beats undertone, peaceful and calming, 60 BPM',
      },
    },
    {
      id: 'music-reggaeton-club',
      title: 'Reggaeton клубный',
      description: 'Латинский ритм для вечеринок',
      mode: 'music',
      iconName: 'Zap',
      modelSlug: 'suno-v5',
      generationMode: 'generate',
      parameters: {
        prompt: 'Reggaeton club track, dembow rhythm, latin bass, 95 BPM, dance floor energy, miami club style',
      },
      badge: 'TREND',
    },
  ],
  tts: [
    {
      id: 'tts-podcast-host',
      title: 'Подкаст ведущий',
      description: 'Профессиональный голос для подкаста',
      mode: 'tts',
      iconName: 'Mic',
      modelSlug: 'elevenlabs-tts',
      generationMode: 'tts',
      parameters: {
        text: 'Привет и добро пожаловать в новый эпизод! Сегодня мы поговорим о самых интересных трендах в мире технологий.',
        voice: 'rachel',
        stability: 0.7,
        style: 'podcast',
      },
      badge: 'POPULAR',
    },
    {
      id: 'tts-audiobook',
      title: 'Аудиокнига рассказчик',
      description: 'Тёплый голос для аудиокниг',
      mode: 'tts',
      iconName: 'Mic',
      modelSlug: 'elevenlabs-tts',
      generationMode: 'tts',
      parameters: {
        text: 'В один прекрасный осенний день, когда листья уже начали желтеть и опадать, герой нашей истории отправился в путешествие.',
        voice: 'daniel',
        stability: 0.8,
        style: 'narrative',
      },
    },
    {
      id: 'tts-ad-energetic',
      title: 'Реклама энергично',
      description: 'Динамичная озвучка для рекламы',
      mode: 'tts',
      iconName: 'Zap',
      modelSlug: 'elevenlabs-tts',
      generationMode: 'tts',
      parameters: {
        text: 'Только сегодня! Невероятная скидка 50% на все товары! Не упустите шанс — предложение ограничено!',
        voice: 'adam',
        stability: 0.4,
        style: 'commercial',
      },
      badge: 'TREND',
    },
    {
      id: 'tts-documentary',
      title: 'Документальный голос',
      description: 'Авторитетный голос документальных фильмов',
      mode: 'tts',
      iconName: 'Mic',
      modelSlug: 'elevenlabs-tts',
      generationMode: 'tts',
      parameters: {
        text: 'На протяжении тысячелетий человечество задавалось вопросом о своём месте во вселенной. Сегодня наука даёт нам новые ответы.',
        voice: 'james',
        stability: 0.75,
        style: 'documentary',
      },
    },
    {
      id: 'tts-childrens-story',
      title: 'Детская сказка',
      description: 'Добрый голос для детских историй',
      mode: 'tts',
      iconName: 'Sparkles',
      modelSlug: 'elevenlabs-tts',
      generationMode: 'tts',
      parameters: {
        text: 'Жил-был маленький медвежонок, который очень любил мёд и приключения. Каждое утро он просыпался и думал: что интересного случится сегодня?',
        voice: 'bella',
        stability: 0.9,
        style: 'friendly',
      },
      badge: 'NEW',
    },
    {
      id: 'tts-humor-pop',
      title: 'Юмористический поп',
      description: 'Весёлый голос для юмористического контента',
      mode: 'tts',
      iconName: 'Zap',
      modelSlug: 'elevenlabs-tts',
      generationMode: 'tts',
      parameters: {
        text: 'А вы знали, что средний человек проводит шесть лет своей жизни в снах? Представьте, это целых шесть лет бесплатных фильмов!',
        voice: 'adam',
        stability: 0.5,
        style: 'humorous',
      },
    },
    {
      id: 'tts-corporate',
      title: 'Корпоративный анонс',
      description: 'Официальный голос для корпоративных видео',
      mode: 'tts',
      iconName: 'Mic',
      modelSlug: 'elevenlabs-tts',
      generationMode: 'tts',
      parameters: {
        text: 'Уважаемые коллеги, сообщаем об важном обновлении в корпоративной политике. Просим ознакомиться с новыми регламентами.',
        voice: 'james',
        stability: 0.8,
        style: 'corporate',
      },
    },
    {
      id: 'tts-youtube-intro',
      title: 'Заставка YouTube',
      description: 'Энергичное вступление для видео',
      mode: 'tts',
      iconName: 'Video',
      modelSlug: 'elevenlabs-tts',
      generationMode: 'tts',
      parameters: {
        text: 'Что происходит, ребята! Вы на канале, где мы делаем невозможное возможным. Ставьте лайк и подписывайтесь, чтобы не пропустить!',
        voice: 'adam',
        stability: 0.45,
        style: 'energetic',
      },
      badge: 'POPULAR',
    },
    {
      id: 'tts-meditation-guide',
      title: 'Гайд для медитации',
      description: 'Тихий и спокойный голос для медитаций',
      mode: 'tts',
      iconName: 'Mic',
      modelSlug: 'elevenlabs-tts',
      generationMode: 'tts',
      parameters: {
        text: 'Сделайте глубокий вдох... и медленно выдохните. Почувствуйте, как с каждым дыханием ваше тело становится расслабленнее.',
        voice: 'bella',
        stability: 0.95,
        style: 'meditation',
      },
    },
    {
      id: 'tts-dramatic-trailer',
      title: 'Драматичный трейлер',
      description: 'Эпичный голос для трейлеров фильмов',
      mode: 'tts',
      iconName: 'Sparkles',
      modelSlug: 'elevenlabs-tts',
      generationMode: 'tts',
      parameters: {
        text: 'Когда всё потеряно. Когда надежды больше нет. Остаётся только один выбор. Этой осенью — приготовьтесь.',
        voice: 'james',
        stability: 0.6,
        style: 'dramatic',
      },
      badge: 'TREND',
    },
  ],
  utility: [
    {
      id: 'util-instagram-carousel',
      title: 'Instagram карусели',
      description: 'Серия 10 связных слайдов под формат Reels/карусели',
      mode: 'utility',
      modelSlug: 'nano-banana-2',
      generationMode: 't2i',
      parameters: {
        prompt: 'Instagram carousel slide design, minimal typography, brand-consistent color palette, 4:5 aspect ratio, social media post',
        aspectRatio: '4:5',
        numberOfImages: 4,
        outputResolution: '2K',
      },
      iconName: 'Image',
      badge: 'POPULAR',
    },
    {
      id: 'util-digital-avatar',
      title: 'Цифровой аватар',
      description: 'Стилизованный портрет-аватар из фотографии или описания',
      mode: 'utility',
      modelSlug: 'flux-2-pro',
      generationMode: 't2i',
      parameters: {
        prompt: 'Professional digital avatar portrait, clean studio lighting, soft gradient background, expressive eyes, head-and-shoulders framing',
        aspectRatio: '1:1',
        outputFormat: 'png',
        outputQuality: 95,
      },
      iconName: 'Sparkles',
      badge: 'NEW',
    },
    {
      id: 'util-cartoon',
      title: 'Создать мультфильм',
      description: 'Анимированная сцена в мультяшном стиле с движением персонажей',
      mode: 'utility',
      modelSlug: 'kling-3',
      generationMode: 't2v',
      parameters: {
        prompt: 'Pixar-style 3D animated cartoon scene, expressive characters, vibrant colors, cinematic camera motion, family-friendly',
        aspectRatio: '16:9',
        duration: '10',
        mode: 'pro',
        enableAudio: true,
      },
      iconName: 'Wand2',
      badge: 'TREND',
    },
    {
      id: 'util-cinema-studio',
      title: 'Киностудия',
      description: 'Голливудский кинокадр с пресетами по жанрам и операторской работе',
      mode: 'utility',
      modelSlug: 'veo-31',
      generationMode: 't2v',
      parameters: {
        prompt: 'Hollywood cinema shot, anamorphic 2.39:1, professional color grading, dramatic three-point lighting, depth of field, 35mm film grain',
        model: 'veo3_quality',
        aspectRatio: '21:9',
        enableAudio: true,
      },
      iconName: 'Video',
      badge: 'NEW',
    },
  ],
};

// Backward compat for legacy FEATURED_PRESETS usage
export const FEATURED_PRESETS = [
  ...PRESETS_BY_MODE.video,
  ...PRESETS_BY_MODE.image,
  ...PRESETS_BY_MODE.music,
  ...PRESETS_BY_MODE.tts,
];
