import type { ModelDefinition, ParameterDef } from "../types";

const commonParameters: ParameterDef[] = [
  {
    key: "prompt",
    label: "Промпт",
    type: "longtext",
    required: true,
    maxLength: 2000,
    visibility: "basic",
  },
  {
    key: "aspectRatio",
    label: "Соотношение сторон",
    type: "aspectRatio",
    required: true,
    defaultValue: "1:1",
    visibility: "basic",
    options: [
      { value: "1:1", label: "1:1", default: true },
      { value: "16:9", label: "16:9" },
      { value: "9:16", label: "9:16" },
      { value: "4:3", label: "4:3" },
      { value: "3:4", label: "3:4" },
      { value: "2:3", label: "2:3" },
      { value: "3:2", label: "3:2" },
      { value: "21:9", label: "21:9" },
    ],
  },
  {
    key: "outputFormat",
    label: "Формат",
    type: "select",
    required: true,
    defaultValue: "jpeg",
    visibility: "basic",
    options: [
      { value: "jpeg", label: "JPEG", default: true },
      { value: "png", label: "PNG" },
      { value: "webp", label: "WebP" },
    ],
  },
  {
    key: "outputQuality",
    label: "Качество",
    type: "slider",
    required: false,
    min: 1,
    max: 100,
    step: 1,
    defaultValue: 80,
    visibility: "advanced",
  },
  {
    key: "promptUpsampling",
    label: "Prompt upsampling",
    description: "Расширить промпт автоматически",
    type: "switch",
    required: false,
    defaultValue: false,
    visibility: "advanced",
  },
  {
    key: "safetyTolerance",
    label: "Safety tolerance",
    type: "slider",
    required: false,
    min: 1,
    max: 6,
    step: 1,
    defaultValue: 2,
    visibility: "advanced",
  },
];

export const flux2Pro: ModelDefinition = {
  id: "flux-2-pro",
  slug: "flux-2-pro",
  name: "Flux 2 Pro",
  provider: "flux",
  category: "image",
  description:
    "Flux 2 Pro — высококачественная генерация изображений с точным следованием промпту и поддержкой режима image-to-image.",
  badges: ["NEW"],
  priority: 1,
  modes: [
    {
      id: "t2i",
      label: "Текст в изображение",
      description: "Изображение из текста",
      parameters: commonParameters,
    },
    {
      id: "i2i",
      label: "Изображение в изображение",
      description: "Стилизация / редактирование исходного кадра",
      parameters: [
        {
          key: "imageUrl",
          label: "Исходное изображение",
          type: "imageUpload",
          required: true,
          accept: ["image/jpeg", "image/png", "image/webp"],
          maxSizeMB: 10,
          visibility: "basic",
        },
        {
          key: "strength",
          label: "Сила изменений",
          type: "slider",
          required: false,
          min: 0,
          max: 1,
          step: 0.05,
          defaultValue: 0.8,
          visibility: "basic",
        },
        ...commonParameters,
      ],
    },
  ],
  pricing: {
    base: 6,
  },
  endpoint: {
    provider: "kie",
    path: "/api/v1/images/flux2/pro-text-to-image",
  },
  outputs: { type: "image", multiple: false },
};
